### ISSUE TITLE
SortableMixin breaks as it uses beforeObserver

### ISSUE THREAD

**Issue by denzo** [emberjs/ember-legacy-controllers#6]
beforeObserver was removed in Ember v2.0.0 https://github.com/emberjs/ember.js/pull/11796

**Comment by rwjblue** [comment]
Thanks for reporting! We'll dig in and figure out a path forward.

**Comment by stefanpenner** [comment]
@rwjblue only the public API is removed, the internals and _ methods i believe remain

@cibernox thoughts?

**Comment by rwjblue** [comment]
Yup. That's how we'll fix it here. :)

**Comment by cibernox** [comment]
@stefanpenner Apparently no, they were deprecated and then removed completely. 

We can copy them in this project or add them back in ember underscored.

**Comment by stefanpenner** [comment]
Sorry. They should have been left but private in ember.  

It should be possible to rewrite this code to not use them though

**Comment by cibernox** [comment]
@denzo can you install this addon from the master branch and confirm that it works? A new release should be published soon.

**Comment by stefanpenner** [comment]
@cibernox are you able to publish? Or do i need to provide some permissions?

**Comment by cibernox** [comment]
Published 0.0.1

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
