### ISSUE TITLE
Ember['default']._LegacyEachView is undefined

### ISSUE THREAD

**Issue by Sonderstorch** [emberjs/ember-legacy-controllers#8]
I'm getting a TypeError (undefined) in `app/initializers/ember-legacy-controllers.js` at

``` js
initialize: function initialize() {
      /**
        Adds support for ArrayController in the legacy {{each}} helper
      */
      Ember['default']._LegacyEachView.reopen({
```

Am I supposed to use legacy views, too? I'm not even using the legacy controller types, just want to have `SortableMixin` back...

**Comment by Sonderstorch** [comment]
I can confirm that installing `ember-legacy-views` resolves this issue.

However, I don't want to have this dependency.

**Comment by rwjblue** [comment]
Ya, understood. We can likely guard the initializer, but we would also have to disable `itemController` functionality (I think)...

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
